import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "@/components/HeaderNav";
import FooterNav from "@/components/FooterNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lazy Nft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <HeaderNav />
          <div className="">
            {children}
          </div>
          <FooterNav />
        </main>
      </body>
    </html>
  );
}
